# Criar usuário (estudante ou professor)
POST http://localhost:3003/user/create
Content-Type: application/json

{
    "category": "student",
    "name": "user",
    "email": "user@labenu.com.br",
    "birthdate": "01/01/2000" 
}

###
# Criar hobby
POST http://localhost:3003/user/create/hobby
Content-Type: application/json

{
    "title": "Codar"
}

###
# Criar especialidade
POST http://localhost:3003/user/create/speciality
Content-Type: application/json

{
    "title": "React000"
}

###
# Criar turma
POST http://localhost:3003/class/create
Content-Type: application/json

{
    "name": "Muñoz",
    "period": "Noturno",
    "startDate": "30/02/2020",
    "endDate": "31/10/2021",
    "module": 1
}

###

GET http://localhost:3003/student/1

###
# Pegar estudantes de uma turma
GET http://localhost:3003/student?className=Epps

###
# Pegar professores de uma turma
GET http://localhost:3003/teacher?className=Epps

###
POST http://localhost:3003/user/class/add
Content-Type: application/json

{
    "category": "student",
    "userId": 1,
    "classId": 1
}

###
POST http://localhost:3003/fake